# Generated by Django 2.1.15 on 2020-11-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settinggroup',
            old_name='name',
            new_name='group_name',
        ),
    ]
