# Generated by Django 2.1.15 on 2021-07-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settinggroup',
            name='prefix',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Prefix'),
        ),
    ]
