# Generated by Django 2.1.15 on 2020-10-14 10:22

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('value', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Application setting',
                'verbose_name_plural': 'Application settings',
            },
        ),
        migrations.CreateModel(
            name='SettingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
            ],
            options={
                'verbose_name': 'Setting group',
                'verbose_name_plural': 'Setting groups',
            },
        ),
        migrations.AddField(
            model_name='applicationsetting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_settings', to='app_settings.SettingGroup', verbose_name='Application settings'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationsetting',
            unique_together={('name', 'group')},
        ),
    ]
