# Generated by Django 3.2.6 on 2023-03-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_auto_20201118_1053'),
        ('app_settings', '0002_settinggroup_prefix'),
    ]

    operations = [
    ]
