# Generated by Django 3.2.6 on 2023-03-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_merge_20230328_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settinggroup',
            name='prefix',
        ),
        migrations.AlterField(
            model_name='applicationsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='settinggroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
